version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 102.134.147.74:8000
    ports:
      - 8000:8000
    env_file:
      - .env.dev
  # db:
  #   image: postgres:13.0-alphine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_django
  #     - POSTGRES_PASSWORD=hello_django
  #     - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:


