# Generated by Django 4.0 on 2022-01-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gender_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(default=50, max_length=100),
        ),
    ]
